Update index.html
fisher60/wungus-guru pull request #3
Opened 2021-09-27 16:08 UTC by Akarys42

2021-09-27 16:13 UTC, ChrisLovering approved these changes

2021-09-27 19:16 UTC, fisher60 commented on site/index.html
> +        <h1>Yes</h1>
```suggestion
        <h1>Never</h1>
```

2021-09-27 19:17 UTC, fisher60 requested changes
Thank you for your contribution. I do not think these changes are in the best interest of this project though. Please make the suggestion changes so we can revisit this. Please track #4 to avoid any potential merge conflicts. We may wish to close one of these PRs in favor of the other one. Would love to see collaboration there.

Thank you again, and have a fantastic day.

2021-09-28 12:37 UTC, Akarys42 commented
Duplicate of #4 even if I was first, duh

2021-09-28 12:37 UTC, closed without merging