fix: make the file correct
fisher60/wungus-guru pull request #4
Opened 2021-09-27 16:12 UTC by vcokltfre

I was too lazy to MITM the requests, so I made a pr instead

2021-09-27 16:13 UTC, ChrisLovering approved these changes
LGTM

2021-09-27 16:16 UTC, Akarys42 approved these changes
That's the quality PR I expected from the UK quality standards

2021-09-27 16:30 UTC, Bluenix2 approved these changes
It is good that the rest of the world gets to take part in some highly trustable UK enginerring among Brexit. Thank you

2021-09-27 19:16 UTC, fisher60 requested changes
Quality of code is far above expected, so very good job. However there are a few things I would like to see changed. I think these changes better capture the spirit of this project and promote the health of multiple communities. Make these changes and we can revisit merging this PR. Thank you.

2021-09-27 19:16 UTC, fisher60 commented on site/index.html
> +        <title>Yes Wungus</title>
```suggestion
        <title>Absolutely No Wungus</title>
```

2021-09-27 19:16 UTC, fisher60 commented on site/index.html
> +        <h1>Wungus!</h1>
```suggestion
        <h1>No Wungus!</h1>
```

2021-10-01 21:08 UTC, fisher60 commented
ye no

2021-10-01 21:08 UTC, closed without merging